Repository alleyinteractive/create-wordpress-project, pull requests merged in 2025-04, with the labels that each got.

#155 Issue-139: Fix ESLint bugs
  .eslintignore
  .eslintrc.js
  configure.php
  plugin-templates/blocks/theme-navigation/edit.tsx
  plugin-templates/entries/slotfills/subheadline/Subheadline.tsx
  tsconfig.eslint.json
Labels: bug, javascript, typescript

#157 Issue-142: Install Missing @types Packages
  package-lock.json
  package.json
Labels: enhancement, typescript

#158 Issue-88: Clean up plugin and theme package.json after configuration
  configure.php
Labels: enhancement, devops

#161 Issue-152: Migrate VIP Deploys to GitHub Actions
  ci-templates/.circleci/config.yml
  ci-templates/.github/workflows/all-pr-tests.yml
  ci-templates/.github/workflows/copy-to-vip.yml
  ci-templates/.github/workflows/deploy-to-pantheon.yml
  ci-templates/.github/workflows/deploy-to-vip-built-branch.yml
  ci-templates/.github/workflows/deploy-to-vip.yml
  configure.php
Labels: enhancement, ci/cd, devops

#165 Issue-126: Hoist Node Dependencies and Dev Dependencies to Root
  .github/workflows/action.yml
  configure.php
Labels: enhancement, ci/cd, javascript
